Repository rhinstaller/kickstart-tests, pull requests merged in 2021-11, with the labels that each got.

#620 Add libvirtd.log to the output logs
  containers/runner/run-kstest
Labels: enhancement

#622 Add -c --connect-shell to launch script
  containers/runner/README.md
  containers/runner/launch
Labels: enhancement

#621 Master fix driverdisk test
  containers/runner/scenario
  driverdisk-disk.sh
  functions.sh
  scripts/launcher/lib/virtual_controller.py
Labels: bug

#626 Mark some of the tests as manual
  hmc.sh
  image-deployment-1.sh
  lvm-luks-1.sh
  lvm-luks-2.sh
  lvm-luks-3.sh
  lvm-luks-4.sh
  part-luks-1.sh
  part-luks-2.sh
  part-luks-3.sh
  part-luks-4.sh
  raid-luks-1.sh
  raid-luks-2.sh
  raid-luks-3.sh
  raid-luks-4.sh
Labels: blocked
